defaults:
  - base_view_sampler

min_distance_between_context_views: 37
max_distance_between_context_views: 48
min_distance_to_context_views: 0
initial_min_distance_between_context_views: 10
initial_max_distance_between_context_views: 10
